### Get all virtual machines, VMSSs, and ARC machines
### 1. Get Virtual Machines
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/providers/Microsoft.Compute/virtualMachines?api-version=2023-03-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 2. Get ARC Machines
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/providers/Microsoft.HybridCompute/machines?api-version=2024-07-10
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 3. Get VM Scale Sets
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/providers/Microsoft.Compute/virtualMachineScaleSets?api-version=2023-03-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json


### Get all virtual machines, VMSSs, and ARC machines in the resource group
### 1. Get Virtual Machines in the resource group
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines?api-version=2021-04-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 2. Get ARC Machines in the resource group
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.HybridCompute/machines?api-version=2022-12-27
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 3. Get VM Scale Sets in the resource group
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachineScaleSets?api-version=2021-04-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json


### Get Defender for Cloud pricing plan
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2024-01-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 1. Get Defender for Cloud pricing plan on virtual machine
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines/{{$dotenv VM_NAME}}/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2024-01-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 2. Get Defender for Cloud pricing plan on VMSS
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachineScaleSets/{{$dotenv VM_NAME}}/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2024-01-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 3. Get Defender for Cloud pricing plan on ARC machine
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.HybridCompute/machines/{{$dotenv VM_NAME}}/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2024-01-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### Change Defender for Cloud pricing plan
### 1. Change the pricing plan of the VM to P1
PUT https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines/{{$dotenv VM_NAME}}/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2024-01-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

{
  "properties": {
    "pricingTier": "Standard",
    "subPlan": "P1"
  }
}

### 2. Change the pricing plan of the VM to Free
PUT https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines/{{$dotenv VM_NAME}}/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2024-01-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

{
  "properties": {
    "pricingTier": "Free"
  }
}

### 3. Change the pricing plan of the VM to existing plan
DELETE https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines/{{$dotenv VM_NAME}}/providers/Microsoft.Security/pricings/VirtualMachines?api-version=2024-01-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### Virtual Machine extension MDE.Windows
### 1. Get all virtual machine extensions
GET https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines/{{$dotenv VM_NAME}}/extensions?api-version=2021-07-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### 2. Install MDE.Windows extension
PUT https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines/{{$dotenv VM_NAME}}/extensions/MDE.Windows?api-version=2021-07-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

{
  "location": "{{$dotenv LOCATION}}",
  "properties": {
    "publisher": "Microsoft.Azure.AzureDefenderForServers",
    "type": "MDE.Windows",
    "typeHandlerVersion": "1.0",
    "autoUpgradeMinorVersion": true,
    "settings": {}
  }
}

### 3. Delete MDE.Windows extension
DELETE https://management.azure.com/subscriptions/{{$dotenv SUBSCRIPTION_ID}}/resourceGroups/{{$dotenv RESOURCE_GROUP_NAME}}/providers/Microsoft.Compute/virtualMachines/{{$dotenv VM_NAME}}/extensions/MDE.Windows?api-version=2021-07-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json

### Get Subscription List
GET https://management.azure.com/subscriptions?api-version=2022-12-01
Authorization: Bearer {{$dotenv AZURE_ACCESS_TOKEN}}
Content-Type: application/json